# Generated by Django 4.2.1 on 2023-06-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wordsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('A', 'Arabic'), ('E', 'English'), ('F', 'French'), ('G', 'German')], max_length=1)),
                ('word', models.CharField(max_length=20)),
                ('definition', models.CharField(max_length=50)),
                ('hint', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('N', 'Normal'), ('H', 'Hard')], default='N', max_length=1)),
                ('nbTimesChosen', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['lang', 'word'],
            },
        ),
        migrations.AddConstraint(
            model_name='wordslist',
            constraint=models.UniqueConstraint(fields=('lang', 'word'), name='unique_word'),
        ),
    ]
